json.id product.id
json.name product.name
json.is_discounted? product.is_discounted?
json.price product.price
json.decimal product.decimal
json.tax product.tax
json.total product.total
json.image_url product.image_url
json.description product.description
json.item_tracker product.item_tracker
json.created_at product.created_at
json.updated_at product.updated_at
